version: "3.8"

services:
  micro-courses:
    container_name: container-micro-ccmpra
    image: micro-ordencompra-app:1.0.0
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8002"
    environment:
      server.port: 8002
      spring.datasource.url: jdbc:mysql://db-mysql:3306/sisdb2025
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db-mysql:
        condition: service_healthy

  db-mysql:
    image: mysql
    container_name: container-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sisdb2025
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ./mysql-data:/var/lib/mysql