# TERCERA VERSION CON .env POR CADA MICROSERVICIO

version: '3.8'

services:
  micro-cursos:
    build:
      context: ./micro-cursos
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mysql
      - cursos
    env_file:
      - ./.env
    networks:
      - host

  cursos:
    build:
      context: ./estudiantes
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - host

  mysql:
    image: mysql:latest
    container_name: mysql-micro-cursos
    ports:
      - "3312:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sisdb2024
      - TZ=America/Guayaquil
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - host

  # Base de datos PostgreSQL para cursos
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: sisdb2024
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - host

  # Front-end con Next.js
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  postgres-data:
    driver: local
