version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_books
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: librarydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  mysql_data:
    driver: local
